
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${client_id}
            client-secret: ${client_password}
            scope:
              - email
              - profile